version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:14.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  pgadmin:
    container_name: PGAdmin4
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@123.com
      PGADMIN_DEFAULT_PASSWORD: user@123

volumes:
  postgres_db: